"""Streamlit UI for the DevOps Reasoning Agent."""

from __future__ import annotations

import difflib
import os

import streamlit as st
from dotenv import load_dotenv

from agent import analyze_failure
from evaluator import TEST_CASES, run_demo_evaluation, run_evaluation
from github_client import (
    GitHubAPIError,
    create_fix_pull_request,
    create_github_issue,
    fetch_failed_job_logs,
    fetch_workflow_yaml_for_run,
    validate_run_id,
)
from guardrails import redact_secrets, validate_write_action
from reasoning_ui import (
    render_analysis_progressive,
    render_reasoning_chain_sidebar,
    run_analysis_with_progress,
)
from sample_logs import SAMPLE_FAILURES

load_dotenv()

st.set_page_config(
    page_title="DevOps Reasoning Agent",
    page_icon="🔧",
    layout="wide",
)

INPUT_SOURCES = ["Paste Log", "Fetch from GitHub", "Try Demo Failures"]


def _format_issue_body(analysis: dict, log_text: str) -> str:
    """Build Markdown content for a GitHub issue."""
    confidence = analysis.get("confidence_score", 0.0)
    verifier = analysis.get("verifier") or {}
    verifier_status = "Approved" if verifier.get("approved") else "Needs review"
    return f"""## DevOps Reasoning Agent Analysis

**Error Type:** `{analysis.get("error_type", "unknown")}` ({analysis.get("error_label", analysis.get("error_type", "unknown"))})
**Subtype:** {analysis.get("error_subtype", "N/A")}
**Summary:** {analysis.get("summary", "N/A")}
**Confidence:** {confidence:.0%}
**Verifier:** {verifier_status}
**Location:** {analysis.get("location", "Unknown")}

### Root Cause
{analysis.get("root_cause", "N/A")}

### Recommended Fix
```
{analysis.get("fix", "N/A")}
```

<details>
<summary>Original Log (truncated)</summary>

```
{redact_secrets(log_text[:4000])}
```
</details>

---
*Generated by DevOps Reasoning Agent — Microsoft Azure AI Foundry*
"""


def _build_fix_file_content(analysis: dict) -> str:
    """Build file content for a suggested-fix pull request."""
    return f"""# DevOps Agent Suggested Fix

**Error Type:** {analysis.get("error_type", "unknown")}
**Location:** {analysis.get("location", "Unknown")}

## Root Cause
{analysis.get("root_cause", "N/A")}

## Recommended Fix
{analysis.get("fix", "N/A")}

---
Generated by DevOps Reasoning Agent
"""


def _resolve_pr_target(analysis: dict) -> dict:
    """Decide whether the Fix PR patches the real workflow file or writes a note.

    Returns a dict with keys: mode ("patch" or "note"), file_path, content,
    original (for diff), and diff_summary.
    """
    metadata = st.session_state.fetch_metadata or {}
    patched = (analysis.get("patched_workflow") or "").strip()
    workflow_path = metadata.get("workflow_path")
    original_yaml = metadata.get("workflow_yaml")

    if patched and workflow_path and str(workflow_path).endswith((".yml", ".yaml")):
        return {
            "mode": "patch",
            "file_path": workflow_path,
            "content": patched if patched.endswith("\n") else patched + "\n",
            "original": original_yaml or "",
            "diff_summary": analysis.get("diff_summary", ""),
        }

    note_path = analysis.get("suggested_file_path") or ".github/devops-agent-suggested-fix.md"
    if not str(note_path).endswith((".md", ".yml", ".yaml")):
        note_path = ".github/devops-agent-suggested-fix.md"
    return {
        "mode": "note",
        "file_path": note_path,
        "content": _build_fix_file_content(analysis),
        "original": "",
        "diff_summary": analysis.get("diff_summary", ""),
    }


def _render_patch_preview(target: dict) -> None:
    """Show a unified diff of the proposed workflow patch."""
    if target["mode"] != "patch":
        return
    st.markdown(f"**Proposed patch to `{target['file_path']}`**")
    if target["diff_summary"]:
        st.caption(target["diff_summary"])

    original_lines = (target["original"] or "").splitlines()
    patched_lines = target["content"].splitlines()
    diff = list(
        difflib.unified_diff(
            original_lines,
            patched_lines,
            fromfile=f"a/{target['file_path']}",
            tofile=f"b/{target['file_path']}",
            lineterm="",
        )
    )
    if diff:
        st.code("\n".join(diff), language="diff")
    else:
        st.info("Proposed file is identical to the current workflow.")


def _analyze_with_options(log_text: str, fetch_metadata: dict | None = None) -> dict:
    """Run analysis with optional workflow context from GitHub fetch."""
    workflow_yaml = None
    workflow_path = None
    failed_job_names = None

    if fetch_metadata:
        failed_job_names = fetch_metadata.get("failed_job_names")
        workflow_path = fetch_metadata.get("workflow_path")
        workflow_yaml = fetch_metadata.get("workflow_yaml")

    def _run(log: str) -> dict:
        return analyze_failure(
            log,
            workflow_yaml=workflow_yaml,
            workflow_path=workflow_path,
            failed_job_names=failed_job_names,
        )

    analysis, _ = run_analysis_with_progress(_run, log_text)
    return analysis


def _render_evaluation_sidebar() -> None:
    """Render evaluation metrics and chart in the sidebar."""
    st.header("Evaluation")
    st.write("Score the agent against built-in test cases.")
    col_demo_eval, col_full_eval = st.columns(2)
    with col_demo_eval:
        if st.button("Run Demo Eval (5)", use_container_width=True):
            with st.spinner("Running demo evaluation..."):
                st.session_state.eval_result = run_demo_evaluation(analyze_failure)
    with col_full_eval:
        if st.button(f"Run Full Eval ({len(TEST_CASES)})", use_container_width=True):
            with st.spinner("Running full evaluation..."):
                st.session_state.eval_result = run_evaluation(analyze_failure)

    if st.session_state.eval_result:
        result = st.session_state.eval_result
        st.metric("Overall Accuracy", f"{result['accuracy']}%")
        st.metric("Error Type Accuracy", f"{result['error_type_accuracy']}%")
        st.metric("Location Accuracy", f"{result['location_accuracy']}%")
        st.metric("Fix Quality", f"{result['fix_accuracy']}%")
        st.write(f"Passed {result['passed']} / {result['total']} test cases")

        chart_data = {
            "Metric": ["Overall", "Error Type", "Location", "Fix Quality"],
            "Accuracy": [
                result["accuracy"],
                result["error_type_accuracy"],
                result["location_accuracy"],
                result["fix_accuracy"],
            ],
        }
        st.bar_chart(chart_data, x="Metric", y="Accuracy")

        for item in result["results"]:
            icon = "✅" if item["passed"] else "❌"
            st.write(f"{icon} {item['name']}: `{item['predicted_error_type']}`")

        st.caption("Detailed report saved to eval_report.json")

    with st.expander("Supported error categories"):
        from error_types import ERROR_TYPE_DEFINITIONS

        for definition in ERROR_TYPE_DEFINITIONS:
            if definition["id"] == "unknown":
                continue
            st.write(f"**{definition['label']}** (`{definition['id']}`) — {definition['description']}")


def main() -> None:
    """Render the Streamlit application."""
    st.title("DevOps Reasoning Agent")
    st.caption("Powered by Microsoft Azure AI Foundry")

    if "analysis" not in st.session_state:
        st.session_state.analysis = None
    if "log_text" not in st.session_state:
        st.session_state.log_text = ""
    if "eval_result" not in st.session_state:
        st.session_state.eval_result = None
    if "fetch_metadata" not in st.session_state:
        st.session_state.fetch_metadata = None

    with st.sidebar:
        demo_mode = st.toggle(
            "Demo mode (offline, no API calls)",
            value=os.getenv("DEMO_MODE", "").strip().lower() in {"1", "true", "yes", "on"},
            help="Serve fast, deterministic analyses without calling Azure. Ideal for reliable live demos.",
        )
        os.environ["DEMO_MODE"] = "1" if demo_mode else "0"
        if demo_mode:
            st.caption("Offline analyzer active — results are instant and deterministic.")
        st.divider()
        render_reasoning_chain_sidebar(4 if st.session_state.analysis else 0)
        st.divider()
        _render_evaluation_sidebar()
        st.divider()
        st.markdown("**Required `.env` variables**")
        st.code(
            "AZURE_ENDPOINT\nAZURE_API_KEY\nAZURE_AGENT_ID\nAZURE_MODEL\nGITHUB_TOKEN",
            language="text",
        )

    input_source = st.radio(
        "Input source",
        INPUT_SOURCES,
        horizontal=True,
        help="Choose exactly one source for analysis.",
    )

    owner = ""
    repo = ""
    run_id = ""
    pasted_log = ""
    demo_log = ""

    if input_source == "Paste Log":
        pasted_log = st.text_area(
            "Workflow log text",
            height=280,
            placeholder="Paste your GitHub Actions failure log here...",
        )

    elif input_source == "Fetch from GitHub":
        st.caption(
            "Find the run ID in GitHub → Actions → failed run → URL contains `/actions/runs/123456789`"
        )
        col1, col2, col3 = st.columns(3)
        with col1:
            owner = st.text_input("Owner", placeholder="octocat")
        with col2:
            repo = st.text_input("Repository", placeholder="Hello-World")
        with col3:
            run_id = st.text_input("Run ID", placeholder="123456789")

        if st.session_state.log_text and st.session_state.fetch_metadata:
            metadata = st.session_state.fetch_metadata
            st.info(
                "Last fetch: "
                f"conclusion={metadata.get('run', {}).get('conclusion', 'unknown')}, "
                f"failed jobs={', '.join(metadata.get('failed_job_names') or ['none'])}, "
                f"log size={len(st.session_state.log_text)} chars"
            )
            with st.expander("Preview fetched logs"):
                preview_lines = st.session_state.log_text.splitlines()[:50]
                st.code("\n".join(preview_lines), language="text")
                if len(st.session_state.log_text.splitlines()) > 50:
                    st.caption("Showing first 50 lines.")

    else:
        st.write("Pick a sample failure to demo the 4-step reasoning chain instantly.")
        sample_labels = [sample["label"] for sample in SAMPLE_FAILURES]
        selected_label = st.selectbox("Demo failure", sample_labels)
        selected_sample = next(
            sample for sample in SAMPLE_FAILURES if sample["label"] == selected_label
        )
        demo_log = selected_sample["log_text"]
        st.code(demo_log, language="text")

    analyze_clicked = st.button("Analyze", type="primary", use_container_width=True)

    if analyze_clicked:
        st.session_state.fetch_metadata = None
        log_text = ""
        fetch_metadata = None

        if input_source == "Paste Log":
            log_text = pasted_log.strip()
            if not log_text:
                st.warning("Paste a workflow log before analyzing.")

        elif input_source == "Try Demo Failures":
            log_text = demo_log.strip()

        elif input_source == "Fetch from GitHub":
            token = os.getenv("GITHUB_TOKEN", "").strip()
            if not token:
                st.error("GITHUB_TOKEN is missing from your .env file.")
            elif not owner or not repo or not run_id:
                st.error("Enter owner, repository, and run ID.")
            else:
                try:
                    validate_run_id(run_id)
                    with st.spinner("Fetching failed job logs from GitHub..."):
                        fetch_result = fetch_failed_job_logs(owner, repo, run_id, token)
                        log_text = fetch_result["log_text"]
                        workflow_path, workflow_yaml = fetch_workflow_yaml_for_run(
                            owner,
                            repo,
                            run_id,
                            token,
                        )
                        fetch_metadata = {
                            **fetch_result,
                            "workflow_yaml": workflow_yaml,
                            "workflow_path": workflow_path or fetch_result.get("workflow_path"),
                        }
                        st.session_state.fetch_metadata = fetch_metadata
                except GitHubAPIError as exc:
                    st.error(str(exc))
                except Exception as exc:
                    st.error(f"Failed to fetch logs: {exc}")

        if log_text:
            st.session_state.log_text = log_text
            st.session_state.analysis = _analyze_with_options(log_text, fetch_metadata)

    if st.session_state.analysis:
        analysis = st.session_state.analysis
        render_analysis_progressive(analysis, analysis.get("verifier"))

        context = analysis.get("log_context") or {}
        if context:
            with st.expander("Parsed Log Context"):
                st.json(
                    {
                        "exit_code": context.get("exit_code"),
                        "failing_step": context.get("failing_step"),
                        "failed_job_names": context.get("failed_job_names"),
                        "github_errors": context.get("github_errors", [])[:5],
                        "error_snippet": context.get("error_snippet", "")[:500],
                        "truncated_log_chars": len(context.get("truncated_log", "")),
                    }
                )

        st.divider()
        st.subheader("GitHub Actions")
        issue_owner = st.text_input("Repo owner", value=owner, key="issue_owner")
        issue_repo = st.text_input("Repo name", value=repo, key="issue_repo")

        pr_target = _resolve_pr_target(analysis)
        if pr_target["mode"] == "patch":
            st.success(
                "A concrete workflow patch is available — the Fix PR will edit "
                f"`{pr_target['file_path']}` directly."
            )
            with st.expander("Preview workflow patch (diff)", expanded=True):
                _render_patch_preview(pr_target)
        else:
            st.caption(
                "No workflow YAML available to patch — the Fix PR will add a "
                "suggested-fix note. Fetch a run from GitHub to enable direct patching."
            )

        approve_fix = st.checkbox("I approve this fix and want to create a GitHub write action")

        col_issue, col_pr = st.columns(2)

        with col_issue:
            if st.button("Create GitHub Issue", use_container_width=True):
                token = os.getenv("GITHUB_TOKEN", "").strip()
                body = _format_issue_body(analysis, st.session_state.log_text)
                allowed, message = validate_write_action(body, approve_fix)
                if not token:
                    st.error("GITHUB_TOKEN is missing from your .env file.")
                elif not issue_owner or not issue_repo:
                    st.error("Enter repository owner and name.")
                elif not allowed:
                    st.error(message)
                else:
                    title = f"[DevOps Agent] {analysis.get('error_type', 'workflow failure')} detected"
                    try:
                        issue_url = create_github_issue(
                            issue_owner,
                            issue_repo,
                            title,
                            body,
                            token,
                        )
                        st.success(f"Issue created: {issue_url}")
                    except GitHubAPIError as exc:
                        st.error(str(exc))
                    except Exception as exc:
                        st.error(f"Failed to create issue: {exc}")

        with col_pr:
            pr_button_label = (
                "Create Fix PR (patch workflow)"
                if pr_target["mode"] == "patch"
                else "Create Fix PR (note)"
            )
            if st.button(pr_button_label, use_container_width=True):
                token = os.getenv("GITHUB_TOKEN", "").strip()
                fix_content = pr_target["content"]
                file_path = pr_target["file_path"]
                pr_body = _format_issue_body(analysis, st.session_state.log_text)
                allowed, message = validate_write_action(fix_content, approve_fix)
                if not token:
                    st.error("GITHUB_TOKEN is missing from your .env file.")
                elif not issue_owner or not issue_repo:
                    st.error("Enter repository owner and name.")
                elif not allowed:
                    st.error(message)
                else:
                    title = f"[DevOps Agent] Fix for {analysis.get('error_type', 'workflow failure')}"
                    try:
                        pr_url = create_fix_pull_request(
                            issue_owner,
                            issue_repo,
                            file_path,
                            fix_content,
                            title,
                            pr_body,
                            token,
                        )
                        st.success(f"Fix PR created: {pr_url}")
                    except GitHubAPIError as exc:
                        st.error(str(exc))
                    except Exception as exc:
                        st.error(f"Failed to create pull request: {exc}")


if __name__ == "__main__":
    main()
